import { useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";

import Card from "@/components/ui/Card";
import Modal from "@/components/ui/Modal";
import PageHeader from "@/components/ui/PageHeader";
import { useBranches } from "@/features/configuracion/sucursales/hooks/useBranches";
import { createUser, getModules, getUsers, setUserStatus, updateUser, type AppUser, type UserData } from "../services/user.service";

export default function UsersPage() {
  const queryClient = useQueryClient();
  const { data: users = [], isLoading, error } = useQuery({ queryKey: ["users"], queryFn: getUsers });
  const { data: modules = [] } = useQuery({ queryKey: ["modules"], queryFn: getModules });
  const { data: branches = [] } = useBranches();
  const [editing, setEditing] = useState<AppUser | null>(null); const [creating, setCreating] = useState(false);
  const refresh = () => queryClient.invalidateQueries({ queryKey: ["users"] });
  if (isLoading) return <Card>Cargando usuarios...</Card>;
  if (error) return <Card className="bg-red-100 text-red-700">No se pudo cargar los usuarios.</Card>;
  return <section className="space-y-6"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><PageHeader title="Usuarios" subtitle="Datos personales, sucursales y permisos por módulo." /><button onClick={() => setCreating(true)} className="rounded-lg bg-blue-600 px-5 py-2 font-medium text-white">+ Nuevo usuario</button></div>
    <Card className="overflow-hidden p-0"><div className="overflow-x-auto"><table className="min-w-full"><thead className="bg-slate-100"><tr><th className="p-3 text-left">Usuario</th><th className="p-3 text-left">Contacto</th><th className="p-3 text-left">Sucursales</th><th className="p-3 text-center">Estado</th><th className="p-3 text-center">Acciones</th></tr></thead><tbody>{users.map((user) => <tr key={user.user_id} className="border-t"><td className="p-3"><p className="font-medium">{user.first_name || user.full_name || "Sin nombre"} {user.last_name || ""}</p><p className="text-sm text-slate-500">@{user.username || "sin_usuario"} · {user.is_general_admin ? "Administrador general" : "Usuario"}</p></td><td className="p-3 text-sm"><p>{user.email}</p>{user.phone && <p className="text-slate-500">{user.phone}</p>}</td><td className="p-3 text-sm">{user.is_general_admin ? "Todas" : branches.filter((branch) => user.branch_ids.includes(branch.id)).map((branch) => branch.name).join(", ") || "Sin acceso"}</td><td className="p-3 text-center">{user.is_active ? "Activo" : "Inactivo"}</td><td className="p-3 text-center"><button onClick={() => setEditing(user)} className="rounded-lg border px-3 py-1 text-sm">Editar</button><button onClick={async () => { await setUserStatus(user.user_id, !user.is_active); refresh(); }} className="ml-2 rounded-lg border px-3 py-1 text-sm">{user.is_active ? "Desactivar" : "Activar"}</button></td></tr>)}</tbody></table></div></Card>
    <Modal size="wide" open={creating} title="Nuevo usuario" onClose={() => setCreating(false)}><UserForm branches={branches} modules={modules} onSave={async (data) => { await createUser(data); refresh(); setCreating(false); }} /></Modal>
    <Modal size="wide" open={Boolean(editing)} title="Editar usuario" onClose={() => setEditing(null)}>{editing && <UserForm user={editing} branches={branches} modules={modules} onSave={async (data) => { await updateUser(editing.user_id, data); refresh(); setEditing(null); }} />}</Modal>
  </section>;
}

function UserForm({ user, branches, modules, onSave }: { user?: AppUser; branches: { id: string; name: string }[]; modules: { code: string; name: string }[]; onSave: (data: UserData) => Promise<void> }) {
  const [firstName, setFirstName] = useState(user?.first_name ?? ""); const [lastName, setLastName] = useState(user?.last_name ?? ""); const [email, setEmail] = useState(user?.email ?? ""); const [username, setUsername] = useState(user?.username ?? ""); const [phone, setPhone] = useState(user?.phone ?? ""); const [address, setAddress] = useState(user?.address ?? ""); const [birthDate, setBirthDate] = useState(user?.birth_date ?? ""); const [password, setPassword] = useState(""); const [isGeneralAdmin, setIsGeneralAdmin] = useState(user?.is_general_admin ?? false); const [branchIds, setBranchIds] = useState<string[]>(user?.branch_ids ?? []); const [moduleCodes, setModuleCodes] = useState<string[]>(user?.module_codes ?? []); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  const age = birthDate ? Math.floor((Date.now() - new Date(`${birthDate}T00:00:00`).getTime()) / 31557600000) : null;
  const toggle = (value: string, current: string[], set: (values: string[]) => void) => set(current.includes(value) ? current.filter((item) => item !== value) : [...current, value]);
  async function submit(event: React.FormEvent) { event.preventDefault(); if (!isGeneralAdmin && !branchIds.length) { setError("Asigne al menos una sucursal."); return; } if (!isGeneralAdmin && !moduleCodes.length) { setError("Asigne al menos un módulo."); return; } if (!user && password.length < 8) { setError("La contraseña debe tener al menos 8 caracteres."); return; } setSaving(true); setError(""); try { await onSave({ firstName, lastName, email, username, phone, address, birthDate, password, isGeneralAdmin, branchIds, moduleCodes }); } catch (reason) { setError(reason instanceof Error ? reason.message : "No se pudo guardar el usuario."); } finally { setSaving(false); } }
  return <form onSubmit={submit} className="space-y-5"><div className="grid gap-4 md:grid-cols-3"><Field label="Nombre"><input required value={firstName} onChange={(e) => setFirstName(e.target.value)} className="w-full rounded-lg border p-3" /></Field><Field label="Apellido"><input required value={lastName} onChange={(e) => setLastName(e.target.value)} className="w-full rounded-lg border p-3" /></Field><Field label="Nombre de usuario"><input required={!user} disabled={Boolean(user)} value={username} onChange={(e) => setUsername(e.target.value)} className="w-full rounded-lg border p-3 disabled:bg-slate-100" />{user && <p className="mt-1 text-xs text-slate-500">No se puede modificar.</p>}</Field></div><div className="grid gap-4 md:grid-cols-3"><Field label="Correo"><input required type="email" value={email} onChange={(e) => setEmail(e.target.value)} className="w-full rounded-lg border p-3" /></Field><Field label="Teléfono"><input value={phone} onChange={(e) => setPhone(e.target.value)} className="w-full rounded-lg border p-3" /></Field><Field label="Fecha de nacimiento"><input type="date" value={birthDate} onChange={(e) => setBirthDate(e.target.value)} className="w-full rounded-lg border p-3" />{age !== null && <p className="mt-1 text-xs text-slate-500">Edad: {age} años</p>}</Field></div><Field label="Dirección"><input value={address} onChange={(e) => setAddress(e.target.value)} className="w-full rounded-lg border p-3" /></Field><Field label={user ? "Nueva contraseña (opcional)" : "Contraseña inicial"}><input required={!user} minLength={user && !password ? undefined : 8} type="password" value={password} onChange={(e) => setPassword(e.target.value)} className="w-full rounded-lg border p-3" /><p className="mt-1 text-xs text-slate-500">{user ? "Déjala vacía para conservar la actual." : "Mínimo 8 caracteres."}</p></Field>
    <label className="flex items-center gap-2 rounded-lg bg-slate-50 p-3"><input type="checkbox" checked={isGeneralAdmin} onChange={(e) => setIsGeneralAdmin(e.target.checked)} /> Administrador general (acceso total)</label>
    {!isGeneralAdmin && <div className="grid gap-5 lg:grid-cols-2"><CheckGroup title="Sucursales autorizadas" items={branches.map((branch) => ({ value: branch.id, label: branch.name }))} selected={branchIds} onToggle={(value) => toggle(value, branchIds, setBranchIds)} /><CheckGroup title="Módulos autorizados" items={modules.map((module) => ({ value: module.code, label: module.name }))} selected={moduleCodes} onToggle={(value) => toggle(value, moduleCodes, setModuleCodes)} /></div>}
    {error && <p className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}<button disabled={saving} className="rounded-lg bg-blue-600 px-5 py-2 text-white disabled:opacity-50">{saving ? "Guardando..." : user ? "Guardar usuario" : "Crear usuario"}</button>
  </form>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div><label className="mb-1 block text-sm font-medium">{label}</label>{children}</div>; }
function CheckGroup({ title, items, selected, onToggle }: { title: string; items: { value: string; label: string }[]; selected: string[]; onToggle: (value: string) => void }) { return <fieldset><legend className="mb-2 font-medium">{title}</legend><div className="grid gap-2">{items.map((item) => <label key={item.value} className="flex items-center gap-2 rounded-lg border p-2"><input type="checkbox" checked={selected.includes(item.value)} onChange={() => onToggle(item.value)} /> {item.label}</label>)}</div></fieldset>; }
