import { useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import Card from "@/components/ui/Card";
import PageHeader from "@/components/ui/PageHeader";
import { useBranch } from "@/hooks/useBranch";
import { addCashMovement, getCashSessions, getSessionMovements, type PaymentMethod } from "@/features/caja/services/cash.service";

export default function ExtraIncomeExpensesPage() {
  const { activeBranch } = useBranch(); const branchId = activeBranch?.id ?? ""; const client = useQueryClient();
  const [kind, setKind] = useState<"income" | "expense">("expense"); const [method, setMethod] = useState<PaymentMethod>("cash"); const [amount, setAmount] = useState(""); const [reason, setReason] = useState(""); const [message, setMessage] = useState<string | null>(null);
  const sessions = useQuery({ queryKey: ["cash-sessions", branchId], queryFn: () => getCashSessions(branchId), enabled: Boolean(branchId) }); const active = sessions.data?.find((session) => session.status === "open");
  const movements = useQuery({ queryKey: ["cash-movements", active?.id], queryFn: () => getSessionMovements(active!.id), enabled: Boolean(active) });
  async function submit(event: React.FormEvent) { event.preventDefault(); if (!active) return; try { await addCashMovement({ cash_session_id: active.id, branch_id: branchId, movement_type: kind, payment_method: method, amount: Number(amount), reason }); setAmount(""); setReason(""); setMessage("Movimiento registrado."); await client.invalidateQueries({ queryKey: ["cash-movements", active.id] }); } catch (error) { setMessage(error instanceof Error ? error.message : "No se pudo registrar el movimiento."); } }
  return <section className="space-y-6"><PageHeader title="Ingresos y egresos extra" subtitle={`Movimientos adicionales de ${activeBranch?.name ?? "la sucursal"}.`} />
    {message && <div className="rounded-lg bg-blue-50 p-4 text-blue-800">{message}</div>}
    {!active ? <Card><p className="text-amber-800">Debe abrir la caja de la sucursal antes de registrar movimientos extra.</p></Card> : <><Card><form onSubmit={submit} className="grid gap-4 md:grid-cols-4 md:items-end"><div><label className="mb-1 block text-sm font-medium">Tipo</label><select value={kind} onChange={(event) => setKind(event.target.value as "income" | "expense")} className="w-full rounded-lg border p-3"><option value="income">Ingreso extra</option><option value="expense">Egreso extra</option></select></div><div><label className="mb-1 block text-sm font-medium">Forma de pago</label><select value={method} onChange={(event) => setMethod(event.target.value as PaymentMethod)} className="w-full rounded-lg border p-3"><option value="cash">Efectivo</option><option value="qr">QR</option><option value="transfer">Transferencia</option><option value="card">Tarjeta</option><option value="other">Otro</option></select></div><div><label className="mb-1 block text-sm font-medium">Monto</label><input required min="0.01" step="0.01" value={amount} onChange={(event) => setAmount(event.target.value)} type="number" className="w-full rounded-lg border p-3" /></div><div><label className="mb-1 block text-sm font-medium">Motivo</label><input required value={reason} onChange={(event) => setReason(event.target.value)} placeholder="Ej. Venta de bolsa" className="w-full rounded-lg border p-3" /></div><button className="rounded-lg bg-blue-600 px-5 py-3 font-medium text-white md:col-span-4">Registrar movimiento</button></form></Card>
      <Card className="overflow-hidden p-0"><div className="border-b bg-slate-50 p-4"><h2 className="font-semibold">Movimientos de la caja abierta</h2></div><table className="min-w-full"><thead className="bg-slate-50 text-sm"><tr><th className="p-3 text-left">Hora</th><th className="p-3 text-left">Tipo</th><th className="p-3 text-left">Motivo</th><th className="p-3 text-right">Monto</th></tr></thead><tbody>{(movements.data ?? []).map((movement) => <tr key={movement.id} className="border-t"><td className="p-3">{new Date(movement.created_at).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}</td><td className="p-3">{movement.movement_type === "income" ? "Ingreso" : "Egreso"}</td><td className="p-3">{movement.reason}</td><td className={`p-3 text-right font-medium ${movement.movement_type === "income" ? "text-green-700" : "text-red-700"}`}>Bs {movement.amount.toFixed(2)}</td></tr>)}</tbody></table></Card>
    </>}
  </section>;
}
